# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_posts', to=settings.AUTH_USER_MODEL, verbose_name='Users read'),
        ),
        migrations.AlterField(
            model_name='subscriptionslist',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to='blog.Blog', verbose_name='Subscriptions'),
        ),
    ]
